 name: Authenticate BoM and repository
 on:
  workflow_dispatch:
 
 
 jobs:
  authenticate:
     runs-on: ubuntu-latest
     steps:
         - uses: actions/checkout@v2
           name: Checkout code

         - name: Authenticate bil of materials
           uses: docker://codenotary/vcn:bom-maven
           with:
             args: a git://. --lc-host ${{ secrets.CNIL_HOST }} --lc-port ${{ secrets.CNIL_GRPC_PORT }} --lc-api-key ${{ secrets.CNIL_API_KEY }} --bom --signerID ghactions --lc-skip-tls-verify

         - name: Deploying after authentication
           # Only runs if authenticate succeeds
           run: echo "Succesful deployment"
