# This is a basic workflow to help you get started with Actions

name: Notarize and authenticate repository and Bill of Materials

# Controls when the workflow will run


on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
      - 'releases/**'
    tags:        
      - v*           # Push events to v1.0, v1.1, and v1.9 tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_notarize:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Build the project
        run: chmod +x ./gradlew && ./gradlew install && mv build/poms/pom-default.xml pom.xml
      
      - name: Notarize Java Maven project with BoM
        # uses: codenotary/vcn-notarize-bom-java-github-action@v1.0.0
        uses: codenotary/vcn-notarize-bom-java-github-action@main
        with:
          asset: git://.
          cnil_host: ${{ secrets.CNIL_HOST }}
          cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
          cnil_api_key: ${{ secrets.CNIL_API_KEY }}
  


  deploy:
    # This job is meant ot succeed, waiting on authentication only after notarizing the repository
    needs: build_and_notarize
    runs-on: ubuntu-latest
    steps:
        # Simulates retrieving an artifact, ideally it has been previously notarized
        - uses: actions/checkout@v2
          name: Checkout code

        - name: VCN Authenticate BOM For Java project
          uses: codenotary/vcn-authenticate-bom-java-github-action@main
          with:
            asset: git://.
            cnil_host: ${{ secrets.CNIL_HOST }}
            cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
            cnil_api_key: ${{ secrets.CNIL_API_KEY }}
            # the signer ID is always required (even if it's the same as the one of the CNIL API key)
            # - hardcode it here
            signer_id: ghactions


        - name: Deploying after authentication
          run: echo "Succesful deployment"
