# This is a basic workflow to help you get started with Actions

name: Notarize and authenticate repository and Bill of Materials

# Controls when the workflow will run


on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
      - 'releases/**'
    tags:        
      - v*           # Push events to v1.0, v1.1, and v1.9 tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_notarize:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Build the project
        run: chmod +x ./gradlew && ./gradlew install

      - name: VCN generate and notarize BoM for maven projects
        uses: docker://codenotary/vcn:bom-maven
        with:
           args: n git://. --lc-host ${{ secrets.CNIL_HOST }} --lc-port ${{ secrets.CNIL_GRPC_PORT }} --lc-api-key ${{ secrets.CNIL_API_KEY }} --bom --lc-skip-tls-verify
  


  deploy:
    # This job is meant ot succeed, waiting on authentication only after notarizing the repository
    needs: build_and_notarize
    runs-on: ubuntu-latest
    steps:
        # Simulates retrieving an artifact, ideally it has been previously notarized
        - uses: actions/checkout@v2
          name: Checkout code

        - name: VCN generate and notarize BoM for Python projects
          uses: docker://codenotary/vcn:bom-maven
          with:
            args: a git://. --lc-host ${{ secrets.CNIL_HOST }} --lc-port ${{ secrets.CNIL_GRPC_PORT }} --lc-api-key ${{ secrets.CNIL_API_KEY }} --bom --signerID ghactions --lc-skip-tls-verify

        - name: Deploying after authentication
          run: echo "Succesful deployment"
