 name: Untrust BoM
 on:
  workflow_dispatch:
 
 
 jobs:
  untrust:
     runs-on: ubuntu-latest
     steps:
         - uses: actions/checkout@v2
           name: Checkout code

         - name: Untrust repository and bill of materials (after a scan fails or some other situation)
           uses: codenotary/vcn-untrust-bom-java-github-action@main
           with:
             asset: git://.
             cnil_host: ${{ secrets.CNIL_HOST }}
             cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
             cnil_api_key: ${{ secrets.CNIL_API_KEY }}
